const mongoose = require('mongoose');
const { Doctor } = require('../models/Doctor');
const config = require('../config');
const logger = require('../utils/logger');

// Comprehensive seed data with 25 doctors
// Repeating locations: Boston, San Francisco, New York, Chicago, Los Angeles
// Repeating specializations: Cardiology, Neurology, Pediatrics, Orthopedics, Dermatology
const sampleDoctors = [
  // BOSTON DOCTORS (5 doctors)
  {
    userId: '507f1f77bcf86cd799439011',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'dr.sarah.johnson@healthcare.com',
    phone: '+1-555-0101',
    specializations: ['Cardiology', 'Internal Medicine'],
    yearsOfExperience: 15,
    consultationFee: 200,
    bio: 'Board-certified cardiologist with 15 years of experience treating heart conditions.',
    address: {
      street: '123 Medical Center Dr',
      city: 'Boston',
      state: 'MA',
      zipCode: '02115',
      country: 'USA',
    },
    qualifications: [
      { degree: 'MD', institution: 'Harvard Medical School', year: 2008 },
      { degree: 'Fellowship in Cardiology', institution: 'Massachusetts General Hospital', year: 2012 },
    ],
    licenses: [{ licenseNumber: 'MA-123456', state: 'Massachusetts', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Hypertension', 'Heart Disease', 'Arrhythmia', 'High Cholesterol'],
    treatedSymptoms: ['Chest Pain', 'Shortness of Breath', 'Palpitations', 'Fatigue'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 127,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439011',
  },
  {
    userId: '507f1f77bcf86cd799439016',
    firstName: 'Robert',
    lastName: 'Anderson',
    email: 'dr.robert.anderson@healthcare.com',
    phone: '+1-555-0116',
    specializations: ['Pediatrics', 'Adolescent Medicine'],
    yearsOfExperience: 12,
    consultationFee: 160,
    bio: 'Experienced pediatrician specializing in child and adolescent healthcare.',
    address: {
      street: '456 Children\'s Hospital Way',
      city: 'Boston',
      state: 'MA',
      zipCode: '02115',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Boston University School of Medicine', year: 2011 }],
    licenses: [{ licenseNumber: 'MA-223456', state: 'Massachusetts', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Asthma', 'Allergies', 'ADHD', 'Growth Disorders'],
    treatedSymptoms: ['Fever', 'Cough', 'Rash', 'Behavioral Issues'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '14:00', isAvailable: true },
    ],
    rating: 4.7,
    reviewCount: 198,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439016',
  },
  {
    userId: '507f1f77bcf86cd799439017',
    firstName: 'Jennifer',
    lastName: 'Lee',
    email: 'dr.jennifer.lee@healthcare.com',
    phone: '+1-555-0117',
    specializations: ['Dermatology'],
    yearsOfExperience: 9,
    consultationFee: 175,
    bio: 'Board-certified dermatologist treating medical and cosmetic skin conditions.',
    address: {
      street: '789 Skin Institute',
      city: 'Boston',
      state: 'MA',
      zipCode: '02116',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Tufts University School of Medicine', year: 2014 }],
    licenses: [{ licenseNumber: 'MA-323456', state: 'Massachusetts', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Acne', 'Eczema', 'Psoriasis', 'Skin Cancer', 'Rosacea'],
    treatedSymptoms: ['Rash', 'Itching', 'Dry Skin', 'Skin Lesions'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '17:00', isAvailable: true },
    ],
    rating: 4.6,
    reviewCount: 145,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439017',
  },
  {
    userId: '507f1f77bcf86cd799439018',
    firstName: 'Thomas',
    lastName: 'Murphy',
    email: 'dr.thomas.murphy@healthcare.com',
    phone: '+1-555-0118',
    specializations: ['Orthopedics', 'Sports Medicine'],
    yearsOfExperience: 16,
    consultationFee: 210,
    bio: 'Orthopedic surgeon specializing in sports injuries and joint reconstruction.',
    address: {
      street: '321 Sports Medical Plaza',
      city: 'Boston',
      state: 'MA',
      zipCode: '02115',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Harvard Medical School', year: 2007 }],
    licenses: [{ licenseNumber: 'MA-423456', state: 'Massachusetts', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Fractures', 'Arthritis', 'Sports Injuries', 'Ligament Tears'],
    treatedSymptoms: ['Joint Pain', 'Swelling', 'Limited Range of Motion', 'Instability'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '07:00', endTime: '13:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 234,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439018',
  },
  {
    userId: '507f1f77bcf86cd799439019',
    firstName: 'Amanda',
    lastName: 'Cooper',
    email: 'dr.amanda.cooper@healthcare.com',
    phone: '+1-555-0119',
    specializations: ['Neurology'],
    yearsOfExperience: 11,
    consultationFee: 190,
    bio: 'Neurologist with expertise in neurological disorders and cognitive health.',
    address: {
      street: '654 Neurology Center',
      city: 'Boston',
      state: 'MA',
      zipCode: '02118',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Harvard Medical School', year: 2012 }],
    licenses: [{ licenseNumber: 'MA-523456', state: 'Massachusetts', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Epilepsy', 'Migraine', 'Parkinsons Disease', 'Multiple Sclerosis'],
    treatedSymptoms: ['Headache', 'Tremors', 'Numbness', 'Memory Loss'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '10:00', endTime: '18:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 176,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439019',
  },

  // SAN FRANCISCO DOCTORS (5 doctors)
  {
    userId: '507f1f77bcf86cd799439012',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'dr.michael.chen@healthcare.com',
    phone: '+1-555-0102',
    specializations: ['Neurology', 'Pain Management'],
    yearsOfExperience: 12,
    consultationFee: 180,
    bio: 'Neurologist specializing in headaches, migraines, and chronic pain management.',
    address: {
      street: '456 Hospital Blvd',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Stanford Medical School', year: 2011 }],
    licenses: [{ licenseNumber: 'CA-654321', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Migraine', 'Epilepsy', 'Neuropathy', 'Multiple Sclerosis'],
    treatedSymptoms: ['Headache', 'Dizziness', 'Numbness', 'Memory Problems'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '10:00', endTime: '18:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 298,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439012',
  },
  {
    userId: '507f1f77bcf86cd799439020',
    firstName: 'Lisa',
    lastName: 'Wang',
    email: 'dr.lisa.wang@healthcare.com',
    phone: '+1-555-0120',
    specializations: ['Cardiology'],
    yearsOfExperience: 14,
    consultationFee: 205,
    bio: 'Interventional cardiologist specializing in minimally invasive heart procedures.',
    address: {
      street: '789 Heart Institute',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'UCSF School of Medicine', year: 2009 }],
    licenses: [{ licenseNumber: 'CA-754321', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Coronary Artery Disease', 'Heart Failure', 'Arrhythmia', 'Valve Disease'],
    treatedSymptoms: ['Chest Pain', 'Shortness of Breath', 'Irregular Heartbeat', 'Fatigue'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '14:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 267,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439020',
  },
  {
    userId: '507f1f77bcf86cd799439021',
    firstName: 'James',
    lastName: 'Rodriguez',
    email: 'dr.james.rodriguez@healthcare.com',
    phone: '+1-555-0121',
    specializations: ['Pediatrics', 'Neonatology'],
    yearsOfExperience: 10,
    consultationFee: 165,
    bio: 'Pediatrician with subspecialty in newborn and infant care.',
    address: {
      street: '321 Children\'s Medical Center',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Stanford Medical School', year: 2013 }],
    licenses: [{ licenseNumber: 'CA-854321', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Newborn Care', 'Infant Feeding Issues', 'Developmental Delays', 'Childhood Infections'],
    treatedSymptoms: ['Fever', 'Crying', 'Poor Weight Gain', 'Breathing Problems'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 312,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439021',
  },
  {
    userId: '507f1f77bcf86cd799439022',
    firstName: 'Patricia',
    lastName: 'Kim',
    email: 'dr.patricia.kim@healthcare.com',
    phone: '+1-555-0122',
    specializations: ['Dermatology', 'Cosmetic Dermatology'],
    yearsOfExperience: 8,
    consultationFee: 170,
    bio: 'Dermatologist specializing in both medical and aesthetic skincare.',
    address: {
      street: '654 Dermatology Clinic',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94104',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'UCSF School of Medicine', year: 2015 }],
    licenses: [{ licenseNumber: 'CA-954321', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Acne', 'Wrinkles', 'Melasma', 'Skin Cancer'],
    treatedSymptoms: ['Breakouts', 'Fine Lines', 'Dark Spots', 'Moles'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '17:00', isAvailable: true },
    ],
    rating: 4.7,
    reviewCount: 189,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439022',
  },
  {
    userId: '507f1f77bcf86cd799439023',
    firstName: 'David',
    lastName: 'Thompson',
    email: 'dr.david.thompson@healthcare.com',
    phone: '+1-555-0123',
    specializations: ['Orthopedics', 'Hand Surgery'],
    yearsOfExperience: 17,
    consultationFee: 215,
    bio: 'Orthopedic surgeon with subspecialty in hand and upper extremity surgery.',
    address: {
      street: '987 Orthopedic Institute',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Stanford Medical School', year: 2006 }],
    licenses: [{ licenseNumber: 'CA-154321', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Carpal Tunnel', 'Fractures', 'Tendonitis', 'Arthritis'],
    treatedSymptoms: ['Hand Pain', 'Wrist Pain', 'Numbness', 'Weakness'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '07:00', endTime: '13:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 201,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439023',
  },

  // NEW YORK DOCTORS (5 doctors)
  {
    userId: '507f1f77bcf86cd799439024',
    firstName: 'Rachel',
    lastName: 'Goldstein',
    email: 'dr.rachel.goldstein@healthcare.com',
    phone: '+1-555-0124',
    specializations: ['Cardiology', 'Preventive Cardiology'],
    yearsOfExperience: 13,
    consultationFee: 195,
    bio: 'Cardiologist focused on preventive care and heart disease management.',
    address: {
      street: '123 Park Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10016',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Columbia University College of Physicians', year: 2010 }],
    licenses: [{ licenseNumber: 'NY-123789', state: 'New York', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Hypertension', 'High Cholesterol', 'Coronary Artery Disease', 'Heart Failure'],
    treatedSymptoms: ['Chest Discomfort', 'Palpitations', 'Fatigue', 'Edema'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 243,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439024',
  },
  {
    userId: '507f1f77bcf86cd799439025',
    firstName: 'Christopher',
    lastName: 'Patel',
    email: 'dr.christopher.patel@healthcare.com',
    phone: '+1-555-0125',
    specializations: ['Neurology', 'Movement Disorders'],
    yearsOfExperience: 15,
    consultationFee: 200,
    bio: 'Neurologist specializing in Parkinsons disease and movement disorders.',
    address: {
      street: '456 Madison Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'NYU Grossman School of Medicine', year: 2008 }],
    licenses: [{ licenseNumber: 'NY-223789', state: 'New York', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Parkinsons Disease', 'Essential Tremor', 'Dystonia', 'Huntingtons Disease'],
    treatedSymptoms: ['Tremors', 'Rigidity', 'Balance Problems', 'Involuntary Movements'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '16:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 187,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439025',
  },
  {
    userId: '507f1f77bcf86cd799439026',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'dr.maria.santos@healthcare.com',
    phone: '+1-555-0126',
    specializations: ['Pediatrics', 'Emergency Medicine'],
    yearsOfExperience: 11,
    consultationFee: 170,
    bio: 'Pediatric emergency medicine specialist with extensive ER experience.',
    address: {
      street: '789 Lexington Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10021',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Cornell Medical College', year: 2012 }],
    licenses: [{ licenseNumber: 'NY-323789', state: 'New York', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Trauma', 'Acute Illnesses', 'Respiratory Infections', 'Allergic Reactions'],
    treatedSymptoms: ['High Fever', 'Difficulty Breathing', 'Severe Pain', 'Seizures'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '14:00', isAvailable: true },
    ],
    rating: 4.7,
    reviewCount: 221,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439026',
  },
  {
    userId: '507f1f77bcf86cd799439027',
    firstName: 'Daniel',
    lastName: 'Cohen',
    email: 'dr.daniel.cohen@healthcare.com',
    phone: '+1-555-0127',
    specializations: ['Dermatology', 'Mohs Surgery'],
    yearsOfExperience: 14,
    consultationFee: 185,
    bio: 'Dermatologic surgeon specializing in skin cancer treatment and Mohs surgery.',
    address: {
      street: '321 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10016',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Mount Sinai School of Medicine', year: 2009 }],
    licenses: [{ licenseNumber: 'NY-423789', state: 'New York', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Skin Cancer', 'Melanoma', 'Basal Cell Carcinoma', 'Squamous Cell Carcinoma'],
    treatedSymptoms: ['Suspicious Moles', 'Skin Lesions', 'Non-healing Sores', 'Changing Spots'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 203,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439027',
  },
  {
    userId: '507f1f77bcf86cd799439028',
    firstName: 'Angela',
    lastName: 'Martinez',
    email: 'dr.angela.martinez@healthcare.com',
    phone: '+1-555-0128',
    specializations: ['Orthopedics', 'Spine Surgery'],
    yearsOfExperience: 18,
    consultationFee: 225,
    bio: 'Orthopedic spine surgeon specializing in minimally invasive spine procedures.',
    address: {
      street: '654 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Columbia University College of Physicians', year: 2005 }],
    licenses: [{ licenseNumber: 'NY-523789', state: 'New York', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Herniated Disc', 'Spinal Stenosis', 'Scoliosis', 'Degenerative Disc Disease'],
    treatedSymptoms: ['Back Pain', 'Neck Pain', 'Radiating Pain', 'Numbness in Extremities'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '07:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 245,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439028',
  },

  // CHICAGO DOCTORS (5 doctors)
  {
    userId: '507f1f77bcf86cd799439029',
    firstName: 'Steven',
    lastName: 'Wilson',
    email: 'dr.steven.wilson@healthcare.com',
    phone: '+1-555-0129',
    specializations: ['Cardiology', 'Electrophysiology'],
    yearsOfExperience: 16,
    consultationFee: 210,
    bio: 'Cardiac electrophysiologist specializing in heart rhythm disorders.',
    address: {
      street: '123 Michigan Avenue',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Northwestern University Feinberg School', year: 2007 }],
    licenses: [{ licenseNumber: 'IL-123456', state: 'Illinois', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Atrial Fibrillation', 'Arrhythmia', 'Tachycardia', 'Bradycardia'],
    treatedSymptoms: ['Irregular Heartbeat', 'Palpitations', 'Dizziness', 'Fainting'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '14:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 198,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439029',
  },
  {
    userId: '507f1f77bcf86cd799439030',
    firstName: 'Nancy',
    lastName: 'Brown',
    email: 'dr.nancy.brown@healthcare.com',
    phone: '+1-555-0130',
    specializations: ['Neurology', 'Headache Medicine'],
    yearsOfExperience: 10,
    consultationFee: 175,
    bio: 'Neurologist specializing in headache and migraine management.',
    address: {
      street: '456 State Street',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60602',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'University of Chicago Pritzker School', year: 2013 }],
    licenses: [{ licenseNumber: 'IL-223456', state: 'Illinois', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Migraine', 'Cluster Headaches', 'Tension Headaches', 'Chronic Daily Headache'],
    treatedSymptoms: ['Severe Headache', 'Nausea with Headache', 'Visual Disturbances', 'Light Sensitivity'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.7,
    reviewCount: 167,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439030',
  },
  {
    userId: '507f1f77bcf86cd799439031',
    firstName: 'Kevin',
    lastName: 'Taylor',
    email: 'dr.kevin.taylor@healthcare.com',
    phone: '+1-555-0131',
    specializations: ['Pediatrics', 'Infectious Disease'],
    yearsOfExperience: 12,
    consultationFee: 165,
    bio: 'Pediatric infectious disease specialist treating complex infections in children.',
    address: {
      street: '789 Wacker Drive',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Northwestern University Feinberg School', year: 2011 }],
    licenses: [{ licenseNumber: 'IL-323456', state: 'Illinois', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Pneumonia', 'Meningitis', 'Sepsis', 'Viral Infections'],
    treatedSymptoms: ['Persistent Fever', 'Severe Cough', 'Lethargy', 'Difficulty Breathing'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 234,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439031',
  },
  {
    userId: '507f1f77bcf86cd799439032',
    firstName: 'Laura',
    lastName: 'Garcia',
    email: 'dr.laura.garcia@healthcare.com',
    phone: '+1-555-0132',
    specializations: ['Dermatology', 'Pediatric Dermatology'],
    yearsOfExperience: 9,
    consultationFee: 160,
    bio: 'Dermatologist specializing in skin conditions affecting infants and children.',
    address: {
      street: '321 Lake Shore Drive',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60611',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'University of Chicago Pritzker School', year: 2014 }],
    licenses: [{ licenseNumber: 'IL-423456', state: 'Illinois', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Eczema', 'Birthmarks', 'Warts', 'Diaper Rash'],
    treatedSymptoms: ['Skin Rash', 'Itching', 'Dry Skin', 'Skin Discoloration'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '17:00', isAvailable: true },
    ],
    rating: 4.6,
    reviewCount: 156,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439032',
  },
  {
    userId: '507f1f77bcf86cd799439033',
    firstName: 'Brian',
    lastName: 'Lewis',
    email: 'dr.brian.lewis@healthcare.com',
    phone: '+1-555-0133',
    specializations: ['Orthopedics', 'Joint Replacement'],
    yearsOfExperience: 19,
    consultationFee: 220,
    bio: 'Orthopedic surgeon specializing in total joint replacement and reconstruction.',
    address: {
      street: '654 Rush Street',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60611',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'Northwestern University Feinberg School', year: 2004 }],
    licenses: [{ licenseNumber: 'IL-523456', state: 'Illinois', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Osteoarthritis', 'Rheumatoid Arthritis', 'Hip Replacement', 'Knee Replacement'],
    treatedSymptoms: ['Joint Pain', 'Stiffness', 'Limited Mobility', 'Chronic Pain'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '07:00', endTime: '13:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 278,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439033',
  },

  // LOS ANGELES DOCTORS (5 doctors)
  {
    userId: '507f1f77bcf86cd799439034',
    firstName: 'Michelle',
    lastName: 'Zhang',
    email: 'dr.michelle.zhang@healthcare.com',
    phone: '+1-555-0134',
    specializations: ['Cardiology', 'Womens Heart Health'],
    yearsOfExperience: 11,
    consultationFee: 185,
    bio: 'Cardiologist focused on heart disease prevention and treatment in women.',
    address: {
      street: '123 Wilshire Boulevard',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90010',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'UCLA David Geffen School of Medicine', year: 2012 }],
    licenses: [{ licenseNumber: 'CA-123987', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Pregnancy-related Heart Issues', 'Hypertension', 'Heart Disease', 'Valve Disease'],
    treatedSymptoms: ['Chest Pain', 'Shortness of Breath', 'Fatigue', 'Swelling'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 211,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439034',
  },
  {
    userId: '507f1f77bcf86cd799439035',
    firstName: 'Robert',
    lastName: 'Jackson',
    email: 'dr.robert.jackson@healthcare.com',
    phone: '+1-555-0135',
    specializations: ['Neurology', 'Stroke Medicine'],
    yearsOfExperience: 14,
    consultationFee: 195,
    bio: 'Neurologist specializing in stroke prevention, treatment, and rehabilitation.',
    address: {
      street: '456 Santa Monica Boulevard',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90025',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'USC Keck School of Medicine', year: 2009 }],
    licenses: [{ licenseNumber: 'CA-223987', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Stroke', 'TIA', 'Vascular Disease', 'Cerebrovascular Disease'],
    treatedSymptoms: ['Sudden Weakness', 'Speech Difficulty', 'Vision Changes', 'Severe Headache'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '16:00', isAvailable: true },
    ],
    rating: 4.9,
    reviewCount: 187,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439035',
  },
  {
    userId: '507f1f77bcf86cd799439036',
    firstName: 'Susan',
    lastName: 'Park',
    email: 'dr.susan.park@healthcare.com',
    phone: '+1-555-0136',
    specializations: ['Pediatrics', 'Allergy and Immunology'],
    yearsOfExperience: 10,
    consultationFee: 160,
    bio: 'Pediatric allergist treating allergies, asthma, and immune system disorders.',
    address: {
      street: '789 Beverly Boulevard',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90036',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'UCLA David Geffen School of Medicine', year: 2013 }],
    licenses: [{ licenseNumber: 'CA-323987', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Food Allergies', 'Asthma', 'Eczema', 'Seasonal Allergies'],
    treatedSymptoms: ['Wheezing', 'Hives', 'Itchy Eyes', 'Runny Nose'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.7,
    reviewCount: 245,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439036',
  },
  {
    userId: '507f1f77bcf86cd799439037',
    firstName: 'Eric',
    lastName: 'Nguyen',
    email: 'dr.eric.nguyen@healthcare.com',
    phone: '+1-555-0137',
    specializations: ['Dermatology', 'Laser Surgery'],
    yearsOfExperience: 7,
    consultationFee: 175,
    bio: 'Dermatologist specializing in laser treatments for skin conditions.',
    address: {
      street: '321 Sunset Boulevard',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90028',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'USC Keck School of Medicine', year: 2016 }],
    licenses: [{ licenseNumber: 'CA-423987', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Acne Scars', 'Pigmentation', 'Vascular Lesions', 'Wrinkles'],
    treatedSymptoms: ['Scarring', 'Uneven Skin Tone', 'Broken Capillaries', 'Aging Signs'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '10:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '18:00', isAvailable: true },
    ],
    rating: 4.6,
    reviewCount: 134,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439037',
  },
  {
    userId: '507f1f77bcf86cd799439038',
    firstName: 'Karen',
    lastName: 'White',
    email: 'dr.karen.white@healthcare.com',
    phone: '+1-555-0138',
    specializations: ['Orthopedics', 'Pediatric Orthopedics'],
    yearsOfExperience: 13,
    consultationFee: 200,
    bio: 'Pediatric orthopedic surgeon treating musculoskeletal conditions in children.',
    address: {
      street: '654 Hollywood Boulevard',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90028',
      country: 'USA',
    },
    qualifications: [{ degree: 'MD', institution: 'UCLA David Geffen School of Medicine', year: 2010 }],
    licenses: [{ licenseNumber: 'CA-523987', state: 'California', expiryDate: new Date('2026-12-31') }],
    treatedConditions: ['Scoliosis', 'Clubfoot', 'Growth Plate Fractures', 'Limb Deformities'],
    treatedSymptoms: ['Limping', 'Bone Pain', 'Deformity', 'Limited Movement'],
    weeklySchedule: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '07:00', endTime: '15:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '07:00', endTime: '15:00', isAvailable: true },
    ],
    rating: 4.8,
    reviewCount: 192,
    isAvailable: true,
    status: 'active',
    createdByUserId: '507f1f77bcf86cd799439038',
  },
];

async function seedDatabase() {
  try {
    // Connect to database
    await mongoose.connect(config.mongodbUri);
    logger.info('🔗 Connected to MongoDB');

    // Clear existing doctors
    const deleteResult = await Doctor.deleteMany({});
    logger.info(`🗑️  Cleared ${deleteResult.deletedCount} existing doctors`);

    // Insert sample doctors
    const doctors = await Doctor.insertMany(sampleDoctors);
    logger.info(`✅ Successfully inserted ${doctors.length} doctors`);

    // Group doctors by city for summary
    const cityCounts = doctors.reduce((acc, doctor) => {
      const city = doctor.address.city;
      acc[city] = (acc[city] || 0) + 1;
      return acc;
    }, {});

    // Group doctors by specialization for summary
    const specializationCounts = {};
    doctors.forEach(doctor => {
      doctor.specializations.forEach(spec => {
        specializationCounts[spec] = (specializationCounts[spec] || 0) + 1;
      });
    });

    logger.info('\n📊 Database Seed Summary:');
    logger.info('========================');
    
    logger.info('\n🏙️  Doctors by City:');
    Object.entries(cityCounts).forEach(([city, count]) => {
      logger.info(`   ${city}: ${count} doctors`);
    });

    logger.info('\n👨‍⚕️  Doctors by Specialization:');
    Object.entries(specializationCounts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([spec, count]) => {
        logger.info(`   ${spec}: ${count} doctors`);
      });

    logger.info('\n📋 Sample Doctor Details:');
    doctors.slice(0, 5).forEach((doctor, index) => {
      logger.info(`   ${index + 1}. Dr. ${doctor.firstName} ${doctor.lastName}`);
      logger.info(`      Specialization: ${doctor.specializations.join(', ')}`);
      logger.info(`      Location: ${doctor.address.city}, ${doctor.address.state}`);
      logger.info(`      Fee: $${doctor.consultationFee}`);
    });

    logger.info('\n🌱 Database seeded successfully!');
    logger.info(`   Total: ${doctors.length} doctors across ${Object.keys(cityCounts).length} cities`);
    
    process.exit(0);
  } catch (error) {
    logger.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

// Run seed if called directly
if (require.main === module) {
  seedDatabase();
}

module.exports = seedDatabase;
